### ISSUE TITLE
Making the I2C stream extensible

### ISSUE THREAD

**Issue by nseidle** [tedyapo/arduino-MLX90393#13]
Other platforms (Teensy, etc) have multiple Wire streams (Wire1, Wire2, etc). It would be nice to add an option to .begin() that allows for other I2C streams.

**Comment by nseidle** [comment]
I attempted to create a separate branch for this but failed. This feature is implemented in pull request #1.

**Comment by tedyapo** [comment]
Nice enhancement; can't have too many ports these days.  Thanks for your work on this!

Do you know why pulling a branch failed? Are there changes required in the way the repo is configured, or was git just being temperamental?

**Comment by nseidle** [comment]
Not sure why the 2nd branch failed: most likely user error ;)
