### ISSUE TITLE
private enums should be public

### ISSUE THREAD

**Issue by udoklein** [tedyapo/arduino-MLX90393#18]
In the header file there are enums which are useful if the (public) low level functions are called. Would it be possible to shift them into the public part of the header file?

**Comment by udoklein** [comment]
Oops, I should have be more detailed. The enum for the register masks and offsets should be public. The command enums are only reasonable if the send command function would also be public. In my opinion making sendCommand public would be convenient for "extra low level access" as well.

**Comment by tedyapo** [comment]
Agreed. Thanks. Fixed in #28
