### ISSUE TITLE
getDigitalFiltering does not set its return value

### ISSUE THREAD

**Issue by udoklein** [tedyapo/arduino-MLX90393#19]
Most probably the line

this->dig_flt = (reg_val & DIG_FLT_MASK) >> DIG_FLT_SHIFT;`

should be

`this->dig_flt = dig_flt = (reg_val & DIG_FLT_MASK) >> DIG_FLT_SHIFT;`

**Comment by tedyapo** [comment]
Yes. Just fixed in api_cleanup branch.
