### ISSUE TITLE
Packaging up for listing on Arduino lib manager

### ISSUE THREAD

**Issue by nseidle** [tedyapo/arduino-MLX90393#43]
Hi Tedy - If I do some work and give you aPR, are you interested in having this repo listed in Arduino lib manager?

**Comment by tedyapo** [comment]
It seems like a good idea, modulo the work involved :-)

If you're stepping up for it, it sounds even better. Sure, let's go for it!

**Comment by nseidle** [comment]
Thanks! I've been digging through it. Once I get it in a good place I'll do a PR.
