### ISSUE TITLE
Bug in convDelayMillis()

### ISSUE THREAD

**Issue by lucadonini96** [tedyapo/arduino-MLX90393#47]
In MLX90393.cpp, line 409

In the method `convDelayMillis()`, the digital filtering parameter is fetched incorrectly:
`const uint8_t dig_flt = (cache.reg[DIG_FLT_MASK] & DIG_FLT_MASK) >> DIG_FLT_SHIFT;`
should read
`const uint8_t dig_flt = (cache.reg[DIG_FLT_REG] & DIG_FLT_MASK) >> DIG_FLT_SHIFT;`

**Comment by tedyapo** [comment]
thank you!

fixed by 4b044b532be969a4464e58fa488459d97248596d
